/* Copyright 2024 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

#include <unistd.h>

#include "common.h"
#include "llama.h"

#include <string>
#include <vector>

/*
 * Vocab model as a byte array, generated by mayhem/build.sh (an assembler .incbin of the vocab
 * .gguf, so a ~10 MB model costs no compile time). Only the selected variant is embedded.
 */
#if defined(FUZZ_AQUILA)
#include "model_header_aquila.h"
#elif defined(FUZZ_BGE)
#include "model_header_bge.h"
#elif defined(FUZZ_COMMAND_R)
#include "model_header_command_r.h"
#elif defined(FUZZ_QWEN2)
#include "model_header_qwen2.h"
#elif defined(FUZZ_SPM)
#include "model_header_spm.h"
#elif defined(FUZZ_BAICHUAN)
#include "model_header_baichuan.h"
#elif defined(FUZZ_DEEPSEEK_CODER)
#include "model_header_deepseek_coder.h"
#elif defined(FUZZ_FALCON)
#include "model_header_falcon.h"
#elif defined(FUZZ_GPT_2)
#include "model_header_gpt_2.h"
#else
#include "model_header_bpe.h"
#endif

#include <setjmp.h>
#include <unistd.h>

llama_model *model;
llama_context *ctx;


jmp_buf fuzzing_jmp_buf;
extern "C" void __wrap_abort(void) { longjmp(fuzzing_jmp_buf, 1); }

// Every trapped GGML_ABORT would otherwise fork gdb to print a backtrace (~0.4 s each).
extern "C" int LLVMFuzzerInitialize(int *, char ***) {
  setenv("GGML_NO_BACKTRACE", "1", 1);
  return 0;
}

static bool init() {

  char filename[256];
  sprintf(filename, "/dev/shm/libfuzzer.%d.guff", getpid());

  FILE *fp = fopen(filename, "wb");
  if (!fp) {
    return false;
  }
#if defined(FUZZ_BGE)
  fwrite(models_ggml_vocab_bert_bge_gguf, models_ggml_vocab_bert_bge_gguf_len,
         1, fp);
#elif defined(FUZZ_SPM)
  fwrite(models_ggml_vocab_llama_spm_gguf, models_ggml_vocab_llama_spm_gguf_len,
         1, fp);
#elif defined(FUZZ_COMMAND_R)
  fwrite(models_ggml_vocab_command_r_gguf, models_ggml_vocab_command_r_gguf_len,
         1, fp);
#elif defined(FUZZ_QWEN2)
  fwrite(models_ggml_vocab_qwen2_gguf, models_ggml_vocab_qwen2_gguf_len, 1, fp);
#elif defined(FUZZ_AQUILA)
  fwrite(models_ggml_vocab_aquila_gguf, models_ggml_vocab_aquila_gguf_len, 1,
         fp);
#elif defined(FUZZ_GPT_2)
  fwrite(models_ggml_vocab_gpt_2_gguf, models_ggml_vocab_gpt_2_gguf_len, 1, fp);
#elif defined(FUZZ_BAICHUAN)
  fwrite(models_ggml_vocab_baichuan_gguf, models_ggml_vocab_baichuan_gguf_len,
         1, fp);
#elif defined(FUZZ_DEEPSEEK_CODER)
  fwrite(models_ggml_vocab_deepseek_coder_gguf,
         models_ggml_vocab_deepseek_coder_gguf_len, 1, fp);
#elif defined(FUZZ_FALCON)
  fwrite(models_ggml_vocab_falcon_gguf, models_ggml_vocab_falcon_gguf_len, 1,
         fp);
#else
  fwrite(models_ggml_vocab_llama_bpe_gguf, models_ggml_vocab_llama_bpe_gguf_len,
         1, fp);
#endif
  // fclose() flushes: a full /dev/shm shows up here as a short write, not as a corrupt vocab.
  bool written = fclose(fp) == 0;

  llama_backend_init();

  auto mparams = llama_model_default_params();
  mparams.vocab_only = true;
  model = written ? llama_load_model_from_file(filename, mparams) : NULL;
  // The vocab is loaded into memory; never leave the 1-11 MB file behind in /dev/shm.
  unlink(filename);

  if (model == NULL) {
    return false;
  }

  auto cparams = llama_context_default_params();
  ctx = llama_new_context_with_model(model, cparams);
  if (ctx == NULL) {
    llama_free_model(model);
    model = NULL;
    return false;
  }
  return true;
}

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  if (size < 2 || size > 4096) {
    return 0;
  }
  bool add_special = data[0] & 0x01;
  bool parse_special = data[0] & 0x01;
  uint8_t v2 = data[1];
  data += 2;
  size -= 2;

  // Skip the input (and retry on the next one) instead of exiting when the vocab cannot be loaded.
  if (ctx == NULL && !init()) {
    return 0;
  }

  std::string payload(reinterpret_cast<const char *>(data), size);

  // NOTE: this harness loads the model with `vocab_only = true` (see init()), so no weight
  // tensors are ever allocated — only the vocab/tokenizer tables exist. Exercising the
  // tokenize/detokenize surface is exactly the intended fuzzing surface here (and matches the
  // OSS-Fuzz upstream fuzz_tokenizer harness, which likewise never calls decode()).
  //
  // A prior version of this harness went on to call llama_batch_get_one()+llama_decode() on the
  // resulting tokens. That is invalid API usage against a vocab_only context: llama_decode()
  // internally falls back to encode() for these vocab-only configs (n_ctx_train == 0), which then
  // builds a compute graph over weight tensors that were never allocated, dereferencing a null
  // pointer (ggml.c: "applying non-zero offset ... to null pointer") on essentially any non-empty
  // token sequence. Because -fsanitize=address,undefined is compiled with
  // -fno-sanitize-recover=all, UBSan's fatal report path calls its own Die()/abort path directly
  // — NOT libc abort() — so it is NOT caught by the __wrap_abort()/setjmp trap below (that trap
  // only intercepts GGML_ASSERT-style libc abort() calls). The result was a 100% reproducible,
  // immediate process kill on the very first fuzzed input that tokenizes to >=1 token, for EVERY
  // tokenizer variant — starving the fuzzer of any real coverage into the tokenizer/detokenizer
  // logic itself (the actual intended target of this harness).
  try {
    if (setjmp(fuzzing_jmp_buf) == 0) {
      std::vector<llama_token> tokens =
          common_tokenize(ctx, payload.c_str(), add_special, parse_special);
      common_detokenize(ctx, tokens);
    }
  } catch (...) {
  }

  return 0;
}
